### ISSUE TITLE
Change link color

### ISSUE THREAD

**Issue by leahcimto** [leahcimto/leahcimto.github.io#10]
Currently, the colors of the links are purple (by default) and are hard to read on the black background. The links should be changed to a lighter color (such as light blue)

**Comment by MTM828** [comment]
In the CSS, add "text-decoration: none; color: powderblue;" (I think, let me know if it doesn't work) and that should fix it. If you want the underline to stay, add underline by using "underline: 1px solid powderblue;".

I might of mistaken with some code.
Also, only **visited** links are like that, for me they're blue (which is the default colour) until I click them, then they switch to purple. You might also want to ma e them change colour on mouse hover.

**Comment by leahcimto** [comment]
implimented
