### ISSUE TITLE
Dark/light mode toggle

### ISSUE THREAD

**Issue by leahcimto** [leahcimto/leahcimto.github.io#17]
Make a dark and light theme that can be toggled from light to dark.

**Comment by MTM828** [comment]
Would you mind if I helped?

**Comment by leahcimto** [comment]
> Would you mind if I helped?

@MTM828 That would be great! I have assigned you to this. Feel free to submit a PR!

**Comment by MTM828** [comment]
@leahcimto OK, thanks! I'll work on the fork then.

**Comment by leahcimto** [comment]
> **EDIT:** I've finished the basic code, but I might make a few minor improvements too.

@MTM828 You can submit the PR whenever you feel like it :)

**Comment by MTM828** [comment]
@leahcimto Done (finally)! Sorry it took so long.

**Comment by leahcimto** [comment]
Closed per #24
