### ISSUE TITLE
this doesn't look right

### ISSUE THREAD

**Issue by Shluffy** [leahcimto/leahcimto.github.io#20]
this doesn't look right
![image](https://user-images.githubusercontent.com/81823039/114554650-f3f3b680-9c34-11eb-9579-84404c19aef3.png)
is it in the wrong place or something?

**Comment by leahcimto** [comment]
I'll fix this today hopefully

**Comment by Shluffy** [comment]
> I'll fix this today hopefully

Okay. Maybe center on the bottom?

**Comment by leahcimto** [comment]
@Shluffy Sorry for being lazy but do you think you could fix it

**Comment by Shluffy** [comment]
> @Shluffy Sorry for being lazy but do you think you could fix it

what needs to be done?

**Comment by leahcimto** [comment]
making the image one line lower and delete the line between the image and licence info or just delete the image

**Comment by Shluffy** [comment]
> making the image one line lower and delete the line between the image and licence info or just delete the image

okay.

**Comment by Shluffy** [comment]
I can do that.

**Comment by leahcimto** [comment]
thx
